image: python:3.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - python -V  # Print out python version for debugging
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv run pip install -r requirements.txt

stages: 
  - test
  - pages
  - build

test:
  stage: test
  script:
  - pipenv run pytest --cov=<project> test/test*.py

build:
  stage: deploy
  script:
    - python setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
  environment:
    name: package
    url: https://page.com/
  only:
    - branches

pages:
  stage: test
  script:
    - cd utils/
    - pip install sphinx sphinx-rtd-theme
    - cd docs ; make html
    - mv build/html/ ${CI_PROJECT_DIR}/public/
  artifacts:
    paths:
      - public
  environment:
    name: pages
    url: https://page.com/
  only:
    - branches
  stage: test